# Generated by Django 3.1.2 on 2020-11-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control', '0001_initial'),
        ('Juego', '0001_initial'),
        ('HistoriaClinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('num_sesion', models.IntegerField(blank=True, null=True)),
                ('preescripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('mano_derecha', models.BooleanField(blank=True, null=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control.control')),
                ('historiaClinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.historiaclinica')),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Juego.juego')),
            ],
        ),
    ]
