# Generated by Django 3.1.2 on 2021-02-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rutina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='mano_derecha',
            field=models.BooleanField(blank=True, null=True, verbose_name=(('true', 'Derecha'), ('false', 'Izquierda'))),
        ),
    ]
