# Generated by Django 3.1.2 on 2021-02-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rutina', '0002_auto_20210204_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='control',
        ),
        migrations.RemoveField(
            model_name='rutina',
            name='juego',
        ),
        migrations.AlterField(
            model_name='rutina',
            name='mano_derecha',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
