# Generated by Django 3.1.2 on 2021-03-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Control', '0003_control_numerosesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('tiempo', models.DateTimeField(blank=True, null=True)),
                ('fechaHora', models.IntegerField(blank=True, null=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control.control')),
            ],
        ),
    ]
