# Generated by Django 3.1.2 on 2021-03-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intento',
            name='fechaHora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intento',
            name='tiempo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
