# Generated by Django 3.1.2 on 2021-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intento', '0005_intento_estadoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='intento',
            name='movabajo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intento',
            name='movabrir',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intento',
            name='movarriba',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intento',
            name='movpuno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
