# Generated by Django 3.1.2 on 2021-01-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historiaClinca',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True),
        ),
    ]
