# Generated by Django 3.1.2 on 2021-01-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0002_paciente_historiaclinca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='historiaClinca',
            new_name='historiaClinica',
        ),
    ]
