# Generated by Django 3.1.2 on 2021-03-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_auto_20210127_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Segimiento',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True),
        ),
    ]
