# Generated by Django 3.1.2 on 2021-03-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0004_paciente_segimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Segimiento',
            new_name='seguimiento',
        ),
    ]
