# Generated by Django 3.1.2 on 2020-11-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Notificacion', '0001_initial'),
        ('Escenario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_definido', models.DateTimeField(blank=True, null=True)),
                ('puntaje_definido', models.IntegerField(blank=True, null=True)),
                ('nivel', models.IntegerField(blank=True, null=True)),
                ('escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Escenario.escenario')),
                ('notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Notificacion.notificacion')),
            ],
        ),
    ]
