# Generated by Django 3.1.2 on 2021-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0002_auto_20210307_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='nombre',
        ),
        migrations.AddField(
            model_name='juego',
            name='urlImagen',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
