# Generated by Django 3.1.2 on 2021-04-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0003_auto_20210410_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='urlImagen',
        ),
    ]
