# Generated by Django 3.1.2 on 2021-04-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0004_remove_juego_urlimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
