# Generated by Django 3.1.2 on 2021-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0005_juego_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='description',
        ),
        migrations.AddField(
            model_name='juego',
            name='urlImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
