# Generated by Django 3.1.2 on 2021-04-10 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0007_auto_20210410_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='urlImage',
        ),
    ]
