# Generated by Django 3.1.2 on 2020-11-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(blank=True, null=True)),
                ('valoracion', models.CharField(blank=True, max_length=300, null=True)),
                ('dolor', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
