# Generated by Django 3.1.2 on 2021-02-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_control_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='numeroSesion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
