# Generated by Django 3.1.2 on 2021-04-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0005_control_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='ordern',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
