# Generated by Django 3.1.2 on 2021-04-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0007_auto_20210411_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='control',
            old_name='order',
            new_name='orden',
        ),
    ]
