# Generated by Django 3.1.2 on 2020-11-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Juego', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_realizado', models.DateTimeField(blank=True, null=True)),
                ('dolor', models.IntegerField(blank=True, null=True)),
                ('fecha_realizado', models.DateField(blank=True, null=True)),
                ('juego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Juego.juego')),
            ],
        ),
    ]
