# Generated by Django 3.1.2 on 2021-03-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Progreso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='dolor',
            new_name='gradoDolor',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='fecha_realizado',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='juego',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='tiempo_realizado',
        ),
    ]
