# Generated by Django 3.1.2 on 2021-03-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0004_control_juego'),
        ('Progreso', '0002_auto_20210307_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='control',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Control.control'),
        ),
    ]
