# Generated by Django 3.1.2 on 2021-04-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progreso', '0003_progreso_control'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progreso',
            old_name='gradoDolor',
            new_name='gradoDolorFinal',
        ),
        migrations.AddField(
            model_name='progreso',
            name='gradoDolorInicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
