# Generated by Django 3.1.2 on 2020-11-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SignosVitales', '0001_initial'),
        ('Provincia', '0001_initial'),
        ('Canton', '0001_initial'),
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Soltero(a)', 'Soltero(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)')], max_length=100, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('dependiente', models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True)),
                ('nombre_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula_representante', models.CharField(blank=True, max_length=20, null=True)),
                ('actividad_fisica', models.CharField(blank=True, max_length=300, null=True)),
                ('alimentacion', models.CharField(blank=True, max_length=300, null=True)),
                ('consumo', models.CharField(blank=True, choices=[('Alcohol', 'Alcohol'), ('Tabaco', 'Tabaco'), ('Drogas', 'Drogas'), ('Otros', 'Otros')], max_length=100, null=True)),
                ('nombre_medicamento', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300, null=True)),
                ('administracion', models.CharField(blank=True, max_length=300, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=300, null=True)),
                ('patologias', models.CharField(blank=True, max_length=300, null=True)),
                ('inter_quirurgica', models.CharField(blank=True, max_length=300, null=True)),
                ('hta', models.CharField(blank=True, max_length=300, null=True)),
                ('dm', models.CharField(blank=True, max_length=300, null=True)),
                ('dislipidemias', models.CharField(blank=True, max_length=300, null=True)),
                ('ecv', models.CharField(blank=True, max_length=300, null=True)),
                ('alergias', models.CharField(blank=True, max_length=300, null=True)),
                ('cancer', models.CharField(blank=True, max_length=300, null=True)),
                ('otros', models.CharField(blank=True, max_length=300, null=True)),
                ('motivo_consulta', models.CharField(blank=True, max_length=400, null=True)),
                ('estado_funcional', models.CharField(blank=True, max_length=300, null=True)),
                ('revision_aparatos', models.CharField(blank=True, max_length=300, null=True)),
                ('inspeccion', models.CharField(blank=True, max_length=300, null=True)),
                ('palpacion', models.CharField(blank=True, max_length=300, null=True)),
                ('flexion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extension', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('signo_schober', models.CharField(blank=True, max_length=300, null=True)),
                ('calificar', models.IntegerField(blank=True, null=True)),
                ('diag_clinico', models.CharField(blank=True, max_length=400, null=True)),
                ('diag_fisioterapeutico', models.CharField(blank=True, max_length=400, null=True)),
                ('examen_complementario', models.CharField(blank=True, max_length=300, null=True)),
                ('diagnostico_clinico', models.CharField(blank=True, max_length=300, null=True)),
                ('pronostico', models.CharField(blank=True, max_length=400, null=True)),
                ('objetivo_inicialI', models.CharField(blank=True, max_length=300, null=True)),
                ('objetivo_intervencionI', models.CharField(blank=True, max_length=300, null=True)),
                ('plan_tratamientoI', models.CharField(blank=True, max_length=300, null=True)),
                ('objetivo_inicialII', models.CharField(blank=True, max_length=300, null=True)),
                ('objetivo_intervencionII', models.CharField(blank=True, max_length=300, null=True)),
                ('plan_tratamientoII', models.CharField(blank=True, max_length=300, null=True)),
                ('objetivo_intervencionIII', models.CharField(blank=True, max_length=300, null=True)),
                ('plan_tratamientoIII', models.CharField(blank=True, max_length=300, null=True)),
                ('plan_cuidadoIII', models.CharField(blank=True, max_length=300, null=True)),
                ('resultados', models.CharField(blank=True, max_length=400, null=True)),
                ('anexos', models.CharField(blank=True, max_length=400, null=True)),
                ('cantonResidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Canton.canton')),
                ('paciente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Paciente.paciente')),
                ('provinciaResidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Provincia.provincia')),
                ('signosVitales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SignosVitales.signosvitales')),
            ],
        ),
    ]
