# Generated by Django 3.1.2 on 2021-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaClinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='signosVitales',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='frec_cardiaca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='frec_respiratoria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='presion_arterial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='talla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
