# Generated by Django 3.1.2 on 2021-03-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RutinaJuego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutinajuego',
            name='nivel1',
        ),
        migrations.RemoveField(
            model_name='rutinajuego',
            name='nivel2',
        ),
    ]
