# Generated by Django 3.1.2 on 2021-03-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0002_auto_20210307_2139'),
        ('Escenario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escenario',
            name='juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Juego.juego'),
        ),
    ]
